$ErrorActionPreference = 'Stop'

$region = 'ap-southeast-2'
$accountId = aws sts get-caller-identity --region $region --query Account --output text
$sourceAnalysisId = '4fd33a0a-6f21-45b3-be9d-9fdec9a9feb1'
$analysisId = 'finops-unit-economics-analysis'
$oldIdentifier = 'CUDOS Dashboard Demo [Synthetic]'
$newIdentifier = 'FinOps Allocation and Unit Economics [Synthetic]'
$newDataSetArn = "arn:aws:quicksight:$region`:$accountId`:dataset/finops-unit-economics-mock"

if ((aws quicksight list-analyses --aws-account-id $accountId --region $region --query "AnalysisSummaryList[?AnalysisId=='$analysisId'].AnalysisId" --output text) -eq $analysisId) {
    $existingStatus = aws quicksight describe-analysis --aws-account-id $accountId --analysis-id $analysisId --region $region --query 'Analysis.Status' --output text
    if ($existingStatus -eq 'CREATION_FAILED') {
        aws quicksight delete-analysis --aws-account-id $accountId --analysis-id $analysisId --region $region --output text | Out-Null
    } else {
        throw "Analysis $analysisId already exists with status $existingStatus. Delete or rename it before running this creation script again."
    }
}

$sourceDefinition = (
    aws quicksight describe-analysis-definition `
        --aws-account-id $accountId `
        --analysis-id $sourceAnalysisId `
        --region $region `
        --output json |
    ConvertFrom-Json
).Definition

$definition = (
    ($sourceDefinition | ConvertTo-Json -Depth 100 -Compress) `
        -replace [regex]::Escape($oldIdentifier), $newIdentifier |
    ConvertFrom-Json
)

# Filter IDs generated by Amazon Quick AI contain unsupported characters when
# submitted back through the CLI. The 6.2 demo is intentionally unfiltered.
$definition.PSObject.Properties.Remove('FilterGroups')
$definition.DataSetIdentifierDeclarations = @(
    [pscustomobject]@{
        Identifier = $newIdentifier
        DataSetArn = $newDataSetArn
    }
)

$sheet = $definition.Sheets[0]
$sheet.Name = 'Allocation and Unit Economics'

function Set-Measure {
    param(
        [object]$measure,
        [string]$fieldId,
        [string]$columnName,
        [bool]$keepFormat
    )

    $measure.NumericalMeasureField.FieldId = $fieldId
    $measure.NumericalMeasureField.Column.DataSetIdentifier = $newIdentifier
    $measure.NumericalMeasureField.Column.ColumnName = $columnName
    $measure.NumericalMeasureField.AggregationFunction = [pscustomobject]@{
        SimpleNumericalAggregation = 'SUM'
    }

    if (-not $keepFormat) {
        $measure.NumericalMeasureField.PSObject.Properties.Remove('FormatConfiguration')
    }
}

function New-CategoricalField {
    param([string]$fieldId, [string]$columnName)

    [pscustomobject]@{
        CategoricalDimensionField = [pscustomobject]@{
            FieldId = $fieldId
            Column = [pscustomobject]@{
                DataSetIdentifier = $newIdentifier
                ColumnName = $columnName
            }
        }
    }
}

# Top-left KPI: cost per 1,000 successful requests.
$unitKpi = $sheet.Visuals[0].KPIVisual
$unitKpi.Title.FormatText.RichText = '<visual-title>Cost per 1,000 Requests (USD)</visual-title>'
Set-Measure $unitKpi.ChartConfiguration.FieldWells.Values[0] 'source.cost_per_1000_requests' 'cost_per_1000_requests' $true

# Top-middle visual: allocation coverage KPI, derived from the same cost rows.
$coverageKpi = (($unitKpi | ConvertTo-Json -Depth 100 -Compress) | ConvertFrom-Json)
$coverageKpi.VisualId = $sheet.Visuals[1].LineChartVisual.VisualId
$coverageKpi.Title.FormatText.RichText = '<visual-title>Allocation Coverage (% of Eligible Cost)</visual-title>'
Set-Measure $coverageKpi.ChartConfiguration.FieldWells.Values[0] 'source.allocation_coverage_percentage' 'allocation_coverage_percentage' $false
$sheet.Visuals[1] = [pscustomobject]@{ KPIVisual = $coverageKpi }

# Bottom-left bar: owner cost allocation.
$bar = $sheet.Visuals[2].BarChartVisual
$bar.Title.FormatText = [pscustomobject]@{ PlainText = 'Eligible Cost by Owner' }
$bar.ChartConfiguration.FieldWells.BarChartAggregatedFieldWells.Category = @(
    (New-CategoricalField 'source.owner_name' 'owner_name')
)
Set-Measure $bar.ChartConfiguration.FieldWells.BarChartAggregatedFieldWells.Values[0] 'source.eligible_cost' 'eligible_cost' $true
$bar.ChartConfiguration.SortConfiguration.CategorySort[0].FieldSort.FieldId = 'source.eligible_cost'
$bar.ChartConfiguration.CategoryLabelOptions = [pscustomobject]@{
    AxisLabelOptions = @(
        [pscustomobject]@{
            CustomLabel = 'Owner'
            ApplyTo = [pscustomobject]@{
                FieldId = 'source.owner_name'
                Column = [pscustomobject]@{ DataSetIdentifier = $newIdentifier; ColumnName = 'owner_name' }
            }
        }
    )
}
$bar.ChartConfiguration.ValueLabelOptions = [pscustomobject]@{
    AxisLabelOptions = @(
        [pscustomobject]@{
            CustomLabel = 'Eligible Cost (USD)'
            ApplyTo = [pscustomobject]@{
                FieldId = 'source.eligible_cost'
                Column = [pscustomobject]@{ DataSetIdentifier = $newIdentifier; ColumnName = 'eligible_cost' }
            }
        }
    )
}

# Bottom-right donut: allocated versus unallocated cost.
$pie = $sheet.Visuals[3].PieChartVisual
$pie.Title.FormatText = [pscustomobject]@{ PlainText = 'Allocation Status - 96.85% Allocated' }
$pie.ChartConfiguration.FieldWells.PieChartAggregatedFieldWells.Category = @(
    (New-CategoricalField 'source.allocation_status' 'allocation_status')
)
Set-Measure $pie.ChartConfiguration.FieldWells.PieChartAggregatedFieldWells.Values[0] 'source.eligible_cost' 'eligible_cost' $true
$pie.ChartConfiguration.SortConfiguration.CategorySort[0].FieldSort.FieldId = 'source.eligible_cost'
$pie.ChartConfiguration.CategoryLabelOptions = [pscustomobject]@{
    AxisLabelOptions = @(
        [pscustomobject]@{
            CustomLabel = 'Allocation Status'
            ApplyTo = [pscustomobject]@{
                FieldId = 'source.allocation_status'
                Column = [pscustomobject]@{ DataSetIdentifier = $newIdentifier; ColumnName = 'allocation_status' }
            }
        }
    )
}
$pie.ChartConfiguration.ValueLabelOptions = [pscustomobject]@{
    AxisLabelOptions = @(
        [pscustomobject]@{
            CustomLabel = 'Eligible Cost (USD)'
            ApplyTo = [pscustomobject]@{
                FieldId = 'source.eligible_cost'
                Column = [pscustomobject]@{ DataSetIdentifier = $newIdentifier; ColumnName = 'eligible_cost' }
            }
        }
    )
}

# Top-right table: allocation drivers. The KPI and donut already carry the
# summary metrics, so this detail table avoids synthetic NULL summary rows.
$table = $sheet.Visuals[4].TableVisual
$table.Title.FormatText.RichText = '<visual-title>Allocation Driver Detail</visual-title>'
$table.ChartConfiguration.FieldWells.TableAggregatedFieldWells.GroupBy = @(
    (New-CategoricalField 'source.owner_name' 'owner_name'),
    (New-CategoricalField 'source.service' 'service'),
    (New-CategoricalField 'source.allocation_status' 'allocation_status')
)
$table.ChartConfiguration.FieldWells.TableAggregatedFieldWells.Values = @(
    [pscustomobject]@{ NumericalMeasureField = [pscustomobject]@{ FieldId = 'source.eligible_cost'; Column = [pscustomobject]@{ DataSetIdentifier = $newIdentifier; ColumnName = 'eligible_cost' }; AggregationFunction = [pscustomobject]@{ SimpleNumericalAggregation = 'SUM' } } }
)
$table.ChartConfiguration.FieldOptions.SelectedFieldOptions = @(
    [pscustomobject]@{ FieldId = 'source.owner_name'; CustomLabel = 'Owner' },
    [pscustomobject]@{ FieldId = 'source.service'; CustomLabel = 'Service' },
    [pscustomobject]@{ FieldId = 'source.allocation_status'; CustomLabel = 'Allocation Status' },
    [pscustomobject]@{ FieldId = 'source.eligible_cost'; CustomLabel = 'Eligible Cost (USD)' }
)
$table.ChartConfiguration.FieldOptions.Order = @(
    'source.owner_name',
    'source.service',
    'source.allocation_status',
    'source.eligible_cost'
)
$table.ChartConfiguration.SortConfiguration.RowSort = @(
    @{ FieldSort = @{ FieldId = 'source.eligible_cost'; Direction = 'DESC' } }
)

$userArn = "arn:aws:quicksight:us-east-1:$accountId`:user/default/DatTran"
$permissions = @(
    @{
        Principal = $userArn
        Actions = @(
            'quicksight:DescribeAnalysis',
            'quicksight:DescribeAnalysisPermissions',
            'quicksight:QueryAnalysis',
            'quicksight:UpdateAnalysis',
            'quicksight:DeleteAnalysis',
            'quicksight:RestoreAnalysis',
            'quicksight:UpdateAnalysisPermissions'
        )
    }
) | ConvertTo-Json -Depth 5 -Compress

$definitionJson = $definition | ConvertTo-Json -Depth 100 -Compress

# The source dashboard has a few axis-label references outside the field wells.
# Rewrite any remaining source columns so the cloned definition is self-contained.
$definitionJson = $definitionJson -replace 'net_unblended_cost', 'eligible_cost'
$definitionJson = $definitionJson -replace '(?<=")owner(?=")', 'owner_name'
$definitionJson = $definitionJson -replace 'source\.owner(?=")', 'source.owner_name'
aws quicksight create-analysis `
    --aws-account-id $accountId `
    --analysis-id $analysisId `
    --name 'FinOps Allocation and Unit Economics [Synthetic] analysis' `
    --definition $definitionJson `
    --permissions $permissions `
    --region $region `
    --query 'AnalysisArn' `
    --output text
